### ISSUE TITLE
App is blocked under Ventura 13.4

### ISSUE THREAD

**Issue by mwhdc** [oterodiaz/qrcoder#1]
Thanks for publishing your app here, I greatly prefer to download from GitHub over the App Store. Unfortunately Apple seems to have flagged your app or one of its components as malware beyond the usual Gatekeeper monitoring. The restriction can't be dismissed from the Privacy & Security pref pane. The alert that appears is attached.

<img width="333" alt="Screenshot 2023-06-23 at 15 38 41" src="https://github.com/oterodiaz/QRCoder/assets/415062/700e36eb-db83-491f-902f-5edecbc6452e">

**Comment by oterodiaz** [comment]
You're seeing that popup because the code-signing certificate the app was signed with has expired, as Apple makes it quite annoying to distribute software without a paid developer account.

After some research, I've uploaded a new binary to the releases page that is completely unsigned (so the certificate can't expire because it doesn't exist), which from my understanding should be able to run on any mac with the usual Privacy and Security workaround you mentioned.

Let me know if you can (or can't) get it working so I can close this issue.

**Comment by mwhdc** [comment]
The unsigned app works with the pref pane override. Thank you!
